#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# AUTOSTART #
#-----------#
#picom --experimental-backend &
picom &
blueman-applet &
pasystray --notify=all instead &
nm-applet &
cbatticon -u 20 -i notification -c "poweroff" -l 15 -r 10 &
xrandr --output HDMI-A-0 --mode 1366x768 --rate 59.79 --output eDP --off &
feh --randomize --bg-fill /home/dmne/Pictures/background &

#xwallpaper --zoom $HOME/.config/herbstluftwm/keys.jpg
#xfce4-power-manager &
polybar -c $HOME/.config/herbstluftwm/polybar_config mainbar-herbst &
#picom --experimental-backend &
picom &
blueman-applet &
pasystray --notify=all instead &
nm-applet &
cbatticon -u 20 -i notification -c "poweroff" -l 15 -r 10 &
xrandr --output HDMI-A-0 --mode 1366x768 --rate 59.79 --output eDP --off &
feh --randomize --bg-fill /home/dmne/Pictures/background &

#xwallpaper --zoom $HOME/.config/herbstluftwm/keys.jpg
#xfce4-power-manager &
polybar -c $HOME/.config/herbstluftwm/polybar_config mainbar-herbst 
# REMOVE ALL EXISTING KEYBINDINGS #
#---------------------------------#
hc keyunbind --all

# KEYBINDINGS #
#-------------#
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# System controls #
#-----------------#
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-w spawn google-chrome-stable
hc keybind $Mod-Return spawn kitty -e fish
hc keybind $Mod-t spawn thunar
hc keybind $Mod-Shift-t spawn kitty -e ranger
hc keybind $Mod-e spawn lapce
hc keybind $Mod-d spawn telegram-desktop
hc keybind $Mod-Shift-o spawn obsidian
hc keybind $Mod-x spawn /usr/bin/clearine
hc keybind $Mod-Return spawn rofi -show drun -show-icons -modi drun,run
#hc keybind $Mod-Shift-c spawn kitty -T logout -e herbst-logout.sh

# multimedia #
#------------#
hc keybind XF86AudioRaiseVolume spawn wpctl set-sink-volume 0 +5%
hc keybind XF86AudioLowerVolume spawn wpctl set-sink-volume 0 -5%
hc keybind XF86AudioMute spawn wpctl set-sink-mute @DEFAULT_SINK@ toggle
#hc keybind XF86AudioPlay spawn playerctl play-pause
#hc keybind XF86AudioNext spawn playerctl next
#hc keybind XF86AudioPrev spawn playerctl previous
#hc keybind $Mod-Control-s spawn playerctl stop

# run launchers #
#---------------#
#hc keybind $Mod-Shift-i spawn kitty -T vsp2 -e vsp2
#hc keybind $Mod-Shift-d spawn kitty -T launch.sh -e launch.sh 

# scratchpads #
#-------------#
#hc keybind $Mod-Control-1 spawn scratch scratchpad 
#hc keybind $Mod-Control-2 spawn scratch FM
#hc keybind $Mod-Control-3 spawn scratch2 qutebrowser 
#hc keybind $Mod-Control-4 spawn scratchpad

# focusing client #
#-----------------#s
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients in tiling and floating mode #
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames #
#------------------#
hc keybind $Mod-u       split   bottom  0.6
hc keybind $Mod-o       split   right   0.6

# let the current frame explode into subframes #
#----------------------------------------------#
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients #
#--------------------------------------#
resizestep=0.02
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags #
#------#
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    hc set_layout horizontal
    hc set default_frame_layout 1
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting #
#-----------#
hc keybind $Mod-r remove
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-z                                                         \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# focus #
#-------#
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# MOUSE #
#-------#
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# THEME #
#-------#
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#ffffff'
hc attr theme.normal.color '#007687'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.active.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.color '#b8b8b8'
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
#hc attr theme.active.inner_color '#3E4A00'
#hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings false
hc set smart_frame_surroundings false
hc set mouse_recenter_gap 0

# RULES #
#-------#
hc unrule -F

# MENUS #
#-------#
hc rule title~'launch.sh' floating=on floatplacement=center floating_geometry=600x800
hc rule title~'vsp2' floating=on floatplacement=center floating_geometry=375x1000
hc rule title~'configs' floating=on floatplacement=center floating_geometry=375x600
hc rule title~'windows' floating=on floatplacement=center floating_geometry=600x300
hc rule title~'logout' floating=on floatplacement=center floating_geometry=320x200

# SCRATCHPADS #
#-------------#
#hc rule title~'scratchpad' floating=on floatplacement=center floating_geometry=1000x500
#hc rule title~'FM' floating=on floatplacement=center floating_geometry=1000x800
#hc rule class~'qutebrowser' floating=on floatplacement=center floating_geometry=1800x1000

hc rule focus=on # normally focus new clients
hc rule floatplacement=center
#hc rule float_geometry=250x100
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on floatplacement=center
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# UNLOCK #
#--------#
hc unlock

#hc detect_monitors
# hc set_monitors 1920x1060+0+20 1920x1060+1920+20 1920x1060+3840+20


# FIND THE PANEL #
#----------------#
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
hc split vertical 0.6; hc remove
